# config/config.yaml

# Hatırlatma bildirimleri için gün sayıları
reminder:
  day_1: 2  # İlk hatırlatma, 2. günde gönderilecek
  day_2: 5  # İkinci hatırlatma, 5. günde gönderilecek
  day_3: 7  # Üçüncü hatırlatma, 7. günde gönderilecek

# Topik silme için maksimum bekleme süresi
deletion:
  day_3: 9  # Eğer topik 9 gün boyunca boş kalırsa otomatik olarak silinecek

# AWS SNS Konfigürasyonu (Lokal ortamda kullanılacaksa, yerel parametrelerle)
aws:
  region: "us-east-1"  # AWS bölgesi
  access_key: "YOUR_ACCESS_KEY"  # AWS Access Key (lokalde test için dummy olabilir)
  secret_key: "YOUR_SECRET_KEY"  # AWS Secret Key (lokalde test için dummy olabilir)

# Admin Email Konfigürasyonu
admin:
  email: "admin@example.com"  # Hatırlatma ve silme bildirimlerinin gönderileceği email adresi

# SMTP Konfigürasyonu (Lokal email sunucusu kullanıyorsanız)
smtp:
  host: "localhost"  # SMTP sunucusu (lokal sunucu kullanıyorsanız "localhost")
  port: 1025  # SMTP sunucusunun port numarası
  username: ""  # SMTP kullanıcı adı (gerekirse)
  password: ""  # SMTP şifresi (gerekirse)
  from_email: "no-reply@example.com"  # Bildirimlerin gönderileceği email adresi


